version: '3.8'
services:
  #django app
  backend_visitas:
    container_name: skynet_ms_visitas
    build: .
    volumes:
      - .:/app
    ports:
      - 8002:8002
    depends_on:
      - db_visitas
      - redis_visitas
  #eventos de kafka
  # queue_cliente:
  #   build: .
  #   command: >
  #     sh -c "python consumer.py"
  #   depends_on:
  #     - db_visitas
 #postgreSQL
  db_visitas:
    image: postgres
    container_name: django_visitas_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: skynet_visitas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5434:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  #redis
  redis_visitas:
    image: redis
    container_name: django_visitas_api_redis
    ports:
      - 6381:6379

#kafka Queue