# Generated by Django 3.2.16 on 2023-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='visita',
            name='servicio',
            field=models.ManyToManyField(blank=True, to='visita.TipoServicio'),
        ),
    ]
