# Generated by Django 3.2.16 on 2023-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_auto_20230610_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='visita',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio'),
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
