# Generated by Django 3.2.16 on 2023-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_auto_20230610_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='punto_partida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion'),
        ),
    ]
