# Generated by Django 3.2.16 on 2023-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0004_auto_20230622_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
    ]
