# Generated by Django 3.2.16 on 2023-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0005_visita_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
